# Generated by Django 5.2.17 on 2026-09-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='address',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
