# Generated by Django 5.2.17 on 2026-09-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_society_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('society_admin', 'Society Admin'), ('accountant', 'Accountant'), ('manager', 'Manager'), ('guard', 'Gate Guard'), ('resident', 'Resident')], max_length=20),
        ),
    ]
